services:
  api:
    command: ["/bin/sh", "/app/scripts/start-api-dev.sh"]
    volumes:
      - ./src:/app/src
      - ./scripts/start-api-dev.sh:/app/scripts/start-api-dev.sh
    environment:
      - TELEGRAM__ENABLED=false
